defunctzombie/zuul

- lib/SauceBrowser.js
I was getting a problem whenever I ran my tests on SauceLabs (locally or from Travis) where the last browser in any series would always show the error "Test did not see a new command for 90 seconds. Timing out." (I don't know if this is the same bug as #76). Upon inspection of the SauceLabs logs, I noticed the last browser was not receiving a quit command (DELETE /session/:id).
In SauceBrowser, prior to df0ed8d, SauceBrowser.shutdown was called by the browser.quit callback upon test completion. Afterwards, it was called outside the callback. Moving it outside seems to allow the tunnel to be shut down prior to the browser receiving its shutdown command, leaving SauceLabs hanging. Downgrading to 1.16.1 fixed the issue.
Seeing as SauceBrowser.shutdown already calls browser.quit, I removed …
> ensure browser.quit finishes before finishing SauceBrowser.shutdown

- lib/SauceBrowser.js
While running iOS tests, I had an error in SauceBrowser when trying to get the test results. Eval returned an error (something about "Return statements are only valid inside functions"; more Sauce logs below if you're curious). I have no idea why that error occurred, but it ended up crashing zuul. When wd's eval encounters an error, [the callback is called without a response object](https://github.com/admc/wd/blob/master/lib/commands.js#L140), so the debug line for the response length throws an error.
I moved the shutdown line into the first error check and removed the superfluous second check. This shouldn't adversely affect the debugging of the response, since if there's an error, there won't be a response.
Sauce logs for curiosity:
```
2092015-01-12 08:02:10:081 - info: [debug] Device …
```
> prevent error in fetching sauce results from crashing zuul

- lib/flatten_browser.js
Let's you specify browser platforms as an array.
Example config:
```
ui: mocha-bdd
browsers: 
- name: chrome
version: [35,38,latest]
platform: [Mac 10.10, Linux, Windows 2012]
```
Also simple `latest` and `oldest` version strings take all the specified platforms if an array is specified, for those platforms that have that browser version available.
> Add support for a platform array

- bin/zuul
- lib/setup.js
- package.json
- The used tunnel type can be plugged in to zuul by specifying the optional argument to `--tunnel`, such as `--tunnel ngrok`, which will require the `zuul-ngrok` package, or `--tunnel localtunnel` (the default when just doing `--tunnel`), which will require `zuul-localtunnel`.
- Additional configuration needed by the specified tunnel type can be put in `.zuul.yml`, such as the `authtoken` option required by `zuul-ngrok`.
Example of additional configuration:
```
ui: mocha-bdd
authtoken: <token here as needed by ngrok>
browsers: 
- name: chrome
version: 29..latest
```
The required `zuul-localtunnel` dependency is not published yet but can be found [here](https://github.com/rase-/zuul-localtunnel). The `ngrok` implementation can be found [here](https://github.com/rase-/zuul-ngrok). To try …
> Make the tunnel pluggable

- lib/SauceBrowser.js
Make the sauce browser use the tunnel option if `sauce_connect` is not defined.
> Fix tunnel options in `SauceBrowser`

- lib/SauceBrowser.js
Fixes unestablished tunnel if no tunnel option specified and not using sauce connect.
> Fix sauce browser default tunnel option value

- lib/builder-browserify.js
If writing a test that depends on a source file that requires additional transforms, like `coffeeify` or `reactify`, the Zuul test runner will fail because the istanbul transform will be applied before the custom transforms in **.zuul.yml**, and throw various parser errors.
Simply place the call to `bundler.transform(istanbul, ...)` **after** the call to `configure(bundler, config.browserify)`.
> Regsiter Istanbul transform after custom Browserify transforms

- lib/builder-browserify.js
Allows specifying transform specific options with the following syntax:
```yaml
browserify:
- transform:
name: reactify
es6: true
- transform: 6to5ify # "normal" syntax, no options
```
> Make it possible to add transform options

- frameworks/tape/client.js
Fixes too early close of the stream if there is a test named `ok` or `fail`.
Fixes https://github.com/defunctzombie/zuul/issues/145
> Close stream only after full summary.

- bin/zuul
- frameworks/tape/client.js
- lib/PhantomBrowser.js
- package.json
- test/index.js
- test/tape/test.js
Context: I wanted to add a feature to zuul (incoming later).
I looked the zuul tests, saw no tape test.
I like tape (you don't, no prob :p)
Added a test, it failed, had to redo the tape/client.js,
we did not call reporter.done() for instance.
Also I did not see any value in our whole message parsing/logging on top
of tap-parser.
This version works well, in local mode, phantomjs, saucelabs.
It even seems to fix corner cases with timeouted tests and failed plans.
I tried to add as many tests as possible, let me know.
PS: while debugging and hacking I found other bugs that I fixed in different commits
> rework tape client, add tape ui tests

- frameworks/tape/client.js
- package.json
- test/index.js
Before this PR, the tape client would not output
1..9
At the end of tests when using phantombrowser for example, because we
closed the stream too early.
I am using tape-finished because that's the only easy way to know when a
tap suite is finished.
Otherwise we would have to parse 1..9, #tests 9 ourselves.
That's what was done before using regexps. now in a module so we do not care.
> fix tape client finished state

- bin/zuul
- Also making sure specifying --tunnel will use more specific options from .zuul.yml and .zuulrc
- Added a --disable-tunnel flag that overrides the specified tunnel option in .zuul.yml and .zuulrc
> Prefer cmd options over .zuul.yml

- bin/zuul
Lists a browser only once, and comma delimited versions and platforms after that with some indentation.
Here is some sample output
> Make the browser list flag print nicer output

- lib/SauceBrowser.js
Following #159. I know you are "down" for hight timeouts so I did not put higher timeouts but only setup admc/wd options as per the doc: https://github.com/admc/wd/#http-configuration--base-url
I cannot guarantee this will fix the .get() timeouts (https://github.com/defunctzombie/zuul/issues/129#issuecomment-72752754) issues but at least we will be more in control of what's hapening.
> put default admc/wd options

- lib/flatten_browser.js
Versions like `6.0` will be considered as just `6` unless they are wrapped in quotes. Let's try the version and an appenden `.0` when finding matching browser versions.
Fixes https://github.com/defunctzombie/zuul/issues/163
> Make browser versions ending with `.0` work

- lib/SauceBrowser.js
And rename `saucebrowser` to just `sauce` in the saucebrowser debug name.
Fixes https://github.com/defunctzombie/zuul/issues/134
> Show browser name and version in sauce debug name

- lib/builder-browserify.js
- package.json
- test/builder-browserify/bar-to-baz-plugin.js
- test/builder-browserify/baz-to-qux-transform.js
- test/builder-browserify/entry.js
- test/builder-browserify/foo-to-bar-transform.js
- test/index.js
I rewrote the configure function in builder-browserify to register browserify options in the same order as they appear in the config.browserify array. This fixes #177.
I added a test to ensure that things are, in fact, registered in order. I just tacked it on the end of the main test file, but if it should be organized a different way, I can change that.
It seems to be working fine with my projects (and fixed the issue I was having with one of them), and all tests are passing. That being said, the builder module doesn't seem to have any existing tests, so I'd ask for a little help making certain it didn't break anything.
> Register browserify config in the same order as zuul.yml

- lib/setup.js
connection header is not always sent, so it causes the following error:
```
TypeError: Cannot call method 'toLowerCase' of undefined
```
here is an example of req.header when using Sauce Connect:
```
{ host: 'localhost:46768',
'content-length': '11',
origin: 'http://localhost:46768',
'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36',
'content-type': 'text/plain;charset=UTF-8',
accept: '*/*',
referer: 'http://localhost:46768/__zuul',
'accept-encoding': 'gzip, deflate',
'accept-language': 'en-US,en;q=0.8',
via: '1.1 tunnel (squid/3.4.6)',
'cache-control': 'max-age=0' }
```
> fix TypeError caused when connection header is absent

- package.json
ref https://github.com/thlorenz/convert-source-map/pull/18
I'm not sure of a good size for `isLarge` length so I chose 1000 arbitrarily.
> update convert-source-map and check for large sources

- lib/builder-browserify.js
- lib/control-app.js
We change builder API from
var builder = makeBuilder()
builder(files, config, cb)
to
var builder = makeBuilder(files, config)
builder(cb)
Which is more in line with how the only current browserify builder is
implemented.
Now it is not intuitive what should happen if builder is supplied with a different config/files arguments. I think it's better to move them into "static" (init) part of builder API so this is inline with how browserify (and even webpack) works.
> Builder api static config

- frameworks/jasmine2/client.js
This pull request fixes https://github.com/defunctzombie/zuul/issues/196
before:
`suiteDone`: called when each describe completes execution
after:
`jasmineDone`: called when the jasmine suite completes execution
----
I'v referenced [event types summary of testing framework](https://github.com/js-reporters/js-reporters/issues/1#issuecomment-54572441).
/cc @vvo @rase-
> fix jasmine2 client finished state

- bin/zuul
We add support for local configuration through JS by looking for a CommonJS
module named `zuul.config.js`.
We exit if we encounter both `.zuul.yml` and `zuul.config.js` as porting from
one to another is straightforward and we don't want to introduce possible
confusion by merging them.
Closes #183.
> Add support for config through js

- bin/zuul
- lib/SauceBrowser.js
with this parameter, as reviewed with a saucelabs developer
(https://github.com/defunctzombie/zuul/commit/358244c4c5f897f2d4f623d1136764d8440542b3#commitcomment-10112592), we will always be using the latest stable "appium" (mobile support of saucelabs) version
I also added a small annoying fix where you did not see the
require('tunnel-') error sometime because we did not check if an error
object was passed to end().
> fix: use semverd appium-version

- lib/Electron.js
Electron is quite noisy so I switched the stderr messages from `console.error` to `debug`.  Btw, this feature is awesome, especially given how slow PhantomJS moves.
> quiet the electron noise

- HISTORY.md
- bin/zuul
- lib/SauceBrowser.js
- lib/zuul.js
+ add browser_output_timeout option, default to no timeout like before
So that cloud testing does not hangs when uncaught exception thrown
or any other funny thing
Related to (but also useful for anyone) substack/tape#127 and
substack/tape#134
This fixes #185
+ add browser_retries option, default to 6 like before
+ some more debugging information to ease .. debugging
> feat: add browser_output_timeout and browser_retries option

- HISTORY.md
- lib/control-app.js
- package.json
two reasons to do so:
- your web application will always gzip responses, so tests serving
gzip packages better mimic production system
- cloud testing (from travis, from your local connection) can timeout
because receiving 1mb+ of JS can take a very long time
> feat: gzip control app responses

- frameworks/mocha/framework.js
I noticed #219 went stale.  Also, mocha has recently switched to using browserify to build.  However, I looked into programmatically generating the build as part of zuul, and it wouldn't work very cleanly because mocha doesn't ship their `support/browser-entry.js` file in their published version.  This means that zuul would have to ship a copy of that file, which seems worse than just shipping the framework because a change in the lib or browser-entry file could break zuul completely.
I've also built the latest browser-compatible file from source because they had a bug in the latest committed build that broke the runner.
If you don't want to use the browserified version, let me know, but I think that this gets zuul closer to building on the fly.
Closes #219 
Closes #201
> add new mocha to zuul

- lib/flatten_browser.js
- test/unit/flatten-browser.js
I'd been wanting a solution to #209 for a little while, and finally had some free time to code it up. It didn't seem like a syntax had been settled on in the issue discussion, so I went with what I'd been thinking about.
This PR allows you to specify a negative number for the start of a browser range. So, for example, if the latest version of a browser is 42, the string `-3..latest` will yield the range 39, 40, 41, and 42 inclusive. This will also work with manually specified versions, like `-2..8.1` for iPhone.
I'm getting a Sauce authentication error when I try to run the full test suite, for some weird reason (my Open Sauce account has been having some issues recently, so it might just be that). That being said, it's a relatively minor tweak to flatten_browser, so I don't expect …
> Allow negative number for start of browser range

- bin/zuul
From:
```
<firefox 40 on Windows 10> console
<firefox 40 on Windows 10> console
ok 14 should be equal
<firefox 40 on Windows 10> console
ok 15 We received a result event
```
To:
```
<firefox 40 on Windows 10> console
ok 14 should be equal
ok 15 We received a result event
<chrome 40 on ..>
````
=> We only display the browsername if it changed since last output.
This might be an issue because I guess on very long test output when looking at the travis log output it might be harder to find what was the browser (you have to scroll up until you get the name).
But since when a browser error we already output the browser name, we should be good.
Help fighting the 4mb limit of travis:
travis-ci/travis-ci#1382
> fix: lower output by stacking browser names

- package.json
This silences a deprecation warning and fixes some security vulnerabilites.
See https://github.com/gotwarlost/istanbul-middleware/pull/20.
> package: update istanbul-middleware to 0.2.1

- lib/setup.js
- package.json
There is a bug of websocket on bouncy module (https://github.com/substack/bouncy/issues/69), and the module hasn't been maintained recently. I think it would be nice to use http-proxy instead.
As far as I tested, this PR can handle websocket properly.
> Replace bouncy with http-proxy

- bin/zuul
The main problem with #249, that it stops the whole execution, and it's not possible to figure out which test or browser have an error.
This temporary fix helped me to figure out the problem:
```
<iphone 7.1 on Mac 10.10> undefined test
Error: SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent. (https://evidqmsasw.localtunnel.me/__zuul/test-bundle.js:10638)
- failed: <iphone 7.1 on Mac 10.10> (0 failed, 0 passed)
```
> Temporary fix for current_test issue (#249)

- bin/zuul
- lib/PhantomBrowser.js
- lib/phantom-run.js
This PR aims at making phantomjs debugging easier:
* add `--phantom-remote-debugger-port=[port]` which maps to phantoms `--remote-debugger-port=[port]`
* add `--phantom-remote-debugger-autorun` which maps to phantoms `--remote-debugger-autorun`
* add `phantom.onError` handler
* process messages from `phantom.onError`, `page.onError` as `exceptions`, exit the phantom run with `1` if an exception occurs
> feat: easier phantomjs debugging

- frameworks/mocha/client.js
This seems to fix the issue with the leaking `msWDfn` global, see #232.
I've tried it in a build that was previously failing consistently and it seems to work.
The workaround proposed here is to whitelist the `msWDfn` global.
> mocha: whitelist the msWDfn global

- package.json
I'm not sure why, but when running `npm install` the installation process gets stuck with the current version of phantomjs. Everything works fine with the latest version.
> package: update phantomjs to 1.9.19

- package.json
Browserify 13 has speed improvements to the buffer module of up to 30%.
Browserify 12 switched exclusively to streams3 across the whole dependency tree, so it's quicker (fewer KBs) to install, and it's streams3 which adds features for some use cases.
Changelog: https://github.com/substack/node-browserify/blob/master/changelog.markdown
> use browserify 13

- lib/PhantomBrowser.js
- package.json
The name was changed at the request of PhantomJS team.
https://github.com/Medium/phantomjs/issues/447#ref-commit-dbf4a91
> Use phantomjs-prebuilt instead of phantomjs

- lib/SauceBrowser.js
Appium [1.5.2](https://github.com/appium/appium/releases/tag/v1.5.2) is now available on Sauce Labs.
> saucebrowser: use appium 1.5.x

- lib/electron-inject.js
It seems without this timeout fix, tests hang when `electron v1.2.0` or higher is installed.
> timeout fix for electron >= v1.2.0

- lib/SauceBrowser.js
Appium 1.5 does not work on OS X 10.9:
```
/Users/luigi/repos/eventemitter3/node_modules/zuul/bin/zuul:328
throw err.message;
^
iphone@7.0: [init({"name":"eventemitter3","tags":[],"browserName":"iphone","version":"7.0","platform":"Mac 10.9","appium-version":"1.5","record-screenshots":false,"record-video":false})] The environment you requested was unavailable.: Appium 1.5.3 does not support Mac 10.9. Please check our platform configurator (https://saucelabs.com/docs/platforms)
```
This patch fixes the issue by not enforcing a specific Appium version.
> saucebrowser: use an environment variable to specify the appium version

- lib/Electron.js
The Electron team is now publishing electron at electron instead of
electron-prebuilt.
Fixes #305.
> Support new 'electron' package (electron-prebuilt is deprecated)

- package.json
This is to get rid to on of the minimatch warnings.
> Bumped yamljs dependency to v0.2.8.

- bin/zuul
- lib/builder-browserify.js
This PR implements a `--no-instrument` configuration flag. This is useful when coverage is desired, but instrumentation happens at a different point in the pipeline; such as using `babel-plugin-istanbul`. This is [how `nyc` solves the same issue](https://github.com/istanbuljs/nyc#use-with-babel-plugin-istanbul-for-es6es7es2015-support).
Example use case: https://github.com/shannonmoeller/babel-browserify-nyc-tape-zuul-isomorphic-demo
> feat: Added --no-instrument option.

- package.json
@defunctzombie I cannot recall why we where linking to your own stacktrace version, what did it fixed that is not fixed inside the original module?
The thing is that right now with yarn I have issues installing zuul, haven't dig into it. I am just almost sure this will solve it.
> Stop using http tarball for stacktrace-js

- bin/zuul
- lib/SauceBrowser.js
- lib/setup.js
- test/integration/sauce-connect-loopback.js
When using Sauce Connect, Safari and Edge [require a workaround](https://support.saucelabs.com/hc/en-us/articles/115002212447-Unable-to-Reach-Application-on-localhost-for-Tests-Run-on-Safari-8-and-9-and-Edge):
> The issue is these browsers will never send localhost URLs via a proxy [..]. You have two options for a workaround. 
> 
> 1. Modify the hosts file in the machine running Sauce Connect Proxy. Just add a fake domain, such as `myname.local`, that points to `127.0.0.1`. Then, point your tests to that URL instead of `localhost`. This will skip the localhost proxy entirely and prevent the issue, and may even improve the performance of your tests. 
> 
> 2. Use the Sauce Connect localhost proxy to connect over a different port. [..]
I opted for the first. This PR adds a `--loopback …
> Support custom loopback hostname
