frameworks/tape/client.js

Fix duplicate arguments console.log bug

---

lib/setup.js

Add debug to show the tunnel used in setup.

Show used tunnel with `debug`

---

frameworks/index.js
frameworks/jasmine2/client.js
frameworks/jasmine2/framework.js

A proof of concept implementation with the jasmine2 framework. Adds the framework code and a modified jasmine1 client to track progress (the API changed a bit) and "boot" jasmine2.

Added a jasmine2 framework

---

frameworks/index.html
lib/control-app.js
lib/setup.js

Exposed in `ZUUL.port`.
Fixes https://github.com/defunctzombie/zuul/issues/139

Expose Zuul support server port

---

frameworks/index.html
lib/control-app.js

Let's assign properties there instead of backwards compatibility

Don't use JSON.parse in index.html

---

lib/SauceBrowser.js
lib/zuul.js

Testing this PR on my projects right now. I know you are down for this, well if it solves my issues that's good

higher retries and timeouts, selenium, saucelabs are slow

---

lib/SauceBrowser.js

linked with #129
Seems to have been trigered by e21cf63

fix implied global `finish_shutdown`

---

bin/zuul
lib/setup.js

This is a rebase and re-open of defunctzombie/zuul#70.
Tests in master seem to fail, and since this is a rebase from that point I see them failing to.
If you point us on how to help fixing, let us know!
Thanks!

Allow using a custom port in phantom.js

---

lib/user-server.js

Want to specify the wait time as bellow.
```yml
server:
cmd: coffee bin/my_server.coffee
cwd: ../my_server
wait: 10000
```

Add "wait" field to .zuul.yml to wait for starting user_server

---

package.json

No need to have tape as a dependency

tape is a dev dep

---

HISTORY.md
package.json

use http tarball for stacktrace.js

---

bin/zuul
lib/Electron.js
lib/electron-inject.js
lib/electron-run.js
lib/zuul.js

Make it possible to run tests in an atom-shell environment.

add electron support using --electron flag

---

lib/zuul.js

http://sauceio.com/index.php/2015/06/more-vms-for-open-sauce/

Default opensauce concurrency is now 5 VMS!

---

lib/control-app.js
package.json

Fixes #210 
Let me know if anything needs to be changed/fixed!

Expand file globs

---

lib/SauceBrowser.js

test proof: https://github.com/vvo/zuul-test-slow-ci/blob/master/test.sh

faster test reporting

---

lib/flatten_browser.js
test/integration/capabilities.js
test/unit/flatten-browser.js

cc @mcous and @defunctzombie :)

fix: always return a uniq list of browser-version-platform

---

bin/zuul
lib/SauceBrowser.js

Not the best algorithm to fix the bug, but it does the trick.

support microsoft edge responses

---

package.json

All the issues in #245 have been fixed:
- https://github.com/gotwarlost/istanbul/pull/467
- https://github.com/gotwarlost/istanbul-middleware/pull/26

package: update istanbul-middleware to 0.2.2

---

package.json

package: update lodash to 3.10.1

---

lib/PhantomBrowser.js

Fall back from phantomjs-prebuilt to phantomjs

---

lib/electron-inject.js
lib/electron-run.js

electron made some breaking changes in 0.35 and testing using zuul stopped working.
This PR adds the changes needed to support electron >= 0.35.

electron api changes >= 0.35

---

package.json

your username changed (a while ago), and this avoids some confusion to the owner of this package :smile:

nit(package.json): update github repository

---

README.md

There are two other projects named Zuul. Remove the confusion.

Disambiguate with other projects named zuul
